version: '3.1'
services:
  db:
    image: "postgres:11.2-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      # user: postgres
      # pw: password
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 90:8080