# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: "postgres:11.2-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 90:8080